Original 제품 페이지
NowonBadminton/BuddhistMarket pull request #3
Opened 2023-09-13 12:41 UTC by judiking1

2023-09-13 12:55 UTC, CubeDr requested changes

2023-09-13 12:55 UTC, CubeDr commented on src/app/collection/page.js
> +};
지금 사용 안하고 있는 것 같은데 일단 빼시고 사용하는 코드 보내실 때 같이 보내주세요.

2023-09-13 12:55 UTC, CubeDr commented on src/app/original/page.js
> +import Link from "next/link";
작은 따옴표

2023-09-13 12:55 UTC, CubeDr commented on src/app/original/page.js
> +const original = [
이것도 지금 사용 안하고 있는 것 같은데 빼주세요

2023-09-13 12:55 UTC, CubeDr commented on src/app/original/[name]/page.js
> +export default function OriginalDetail({params: { name }}){
`export default function OriginalDetail({params: {name}}) {`

2023-09-14 01:55 UTC, judiking1 commented on src/app/original/page.js
> +const original = [
이거 쓰구있는데! 얘 slice로 잘라서 top3랑 after4 로 쓰는중

2023-09-14 01:59 UTC, judiking1 commented on src/app/collection/page.js
> +};
이거 페이지넘어올때 title 태그에 이름 넣어주는 거라 사용은 되고 있는데 지웡?

2023-09-14 06:03 UTC, CubeDr commented on src/app/collection/page.js
> +};
아 next.js에서 사용되는건가보군요. 알겠습니다.

2023-09-14 06:05 UTC, CubeDr requested changes

2023-09-14 06:05 UTC, CubeDr commented on src/app/original/page.js
> +const original = [
아 아래쪽에 있었군요. 그럼 클래스로 분리하는게 좋을 것 같습니다. 상품 설명이니까 `Product` 클래스 정도로 분리합시다.

2023-09-17 13:22 UTC, CubeDr requested changes

2023-09-17 13:22 UTC, CubeDr commented on src/app/content/product/original.js
> +    new Product(7, ProductType.ORIGINAL, "7위", "/images/7.jpg"),
작은 따옴표

2023-09-17 13:22 UTC, CubeDr commented on src/app/content/product/original.js
>  ];
파일 맨 밑에 빈 줄

2023-09-17 13:22 UTC, CubeDr commented on src/app/content/product/product.js
> +
불필요한 빈 줄 제거

2023-09-17 13:22 UTC, CubeDr commented on src/app/globals.css
> +}
파일 밑에 빈 줄 추가

2023-09-17 13:22 UTC, CubeDr commented on src/app/page.js
> +import Image from 'next/image';
파일 리포맷 해주세요

2023-09-17 15:22 UTC, CubeDr requested changes

2023-09-17 15:22 UTC, CubeDr commented on src/app/content/product/product.js
> +};
클래스와 메서드에는 세미콜론을 붙이지 않습니다.

2023-09-17 15:22 UTC, CubeDr commented on src/app/globals.css
> +};
css에는 세미콜론 붙이지 않습니다.

2023-09-17 15:22 UTC, CubeDr commented on src/app/page.js
>  export default function Home() {
리포맷 하신건가요? 다른 파일을은 인덴트가 4칸인데 이 파일만 2칸입니다.
통일 시켜야 할 것 같습니다.

2023-09-17 15:32 UTC, judiking1 commented on src/app/page.js
>  export default function Home() {
했는데 안바뀌더라고. 인위적으로 칸을 늘려야겠구나 그럼

2023-09-17 15:34 UTC, judiking1 commented on src/app/page.js
>  export default function Home() {
왜그런진 모르겟는데 이 페이지만 인덴트 칸 기준이 달라

<img width="625" alt="image" src="https://github.com/NowonBadminton/BuddhistMarket/assets/110409369/2d1a061f-95f8-40c7-8dac-2bf4d312341c">

2023-09-17 16:02 UTC, CubeDr approved these changes

2023-09-17 16:27 UTC, merged