Login page PR
NowonBadminton/BuddhistMarket pull request #4
Opened 2023-09-18 10:16 UTC by judiking1

2023-09-18 11:31 UTC, CubeDr requested changes

2023-09-18 11:31 UTC, CubeDr commented on src/app/components/Header.js
> +            alert("logout error : " + error);
작은 따옴표

2023-09-18 11:31 UTC, CubeDr commented on src/app/firebase.js
> +import { getAuth, signOut, GoogleAuthProvider, GithubAuthProvider, onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signInWithPopup } from "firebase/auth";
작은 따옴표

2023-09-18 11:31 UTC, CubeDr commented on src/app/firebase.js
> +export {auth, signOut, googleProvider, githubProvider, GoogleAuthProvider, GithubAuthProvider, onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signInWithPopup};
이 파일에서 선언하는 것만 export 하고 나머지는 `firebase/auth`에서 import 해서 사용하세요

2023-09-18 11:31 UTC, CubeDr commented on src/app/firebase.js
> +export {auth, signOut, googleProvider, githubProvider, GoogleAuthProvider, GithubAuthProvider, onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signInWithPopup};
파일 마지막에 빈 줄

2023-09-18 11:31 UTC, CubeDr commented on src/app/globals.css
> +        @apply bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:plac
어떻게 여러 줄로 보기 쉽게 쓸 수 있는 방법 없나요?

2023-09-18 11:31 UTC, CubeDr commented on src/app/login/page.js
> +                alert("error :" + errorMessage + email + credential);
작은 따옴표

2023-09-18 11:31 UTC, CubeDr commented on src/app/login/page.js
> +    const signIn = (e) => {
`signIn`은 로그인을 하는건데, 이 작업에는 이벤트가 필요하지 않습니다.
`onEmailSignInClick`과 `emailSignIn`을 나누어 각각 역할에 맞는 처리를 해주도록 분리해주세요.

또, login과 signin이 혼용되고 있는데 하나로 통일해주세요.

2023-09-18 11:31 UTC, CubeDr commented on src/app/login/page.js
> +            if (user) {
early-out

2023-09-18 11:31 UTC, CubeDr commented on src/app/login/page.js
> +                alert("error :" + errorMessage + email + credential);
작은 따옴표

2023-09-18 11:31 UTC, CubeDr commented on src/app/login/page.js
> +        signInWithPopup(auth, githubProvider)
`googleLogin`과 로직이 똑같습니다. 코드 중복을 피할 수 있는 방법을 생각해보세요.

2023-09-18 11:31 UTC, CubeDr commented on src/app/login/sign/page.js
> +    const reg = /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[~?!@#$%^&*_-]).{8,}$/;
함수 밖으로 빼주세요

2023-09-18 11:31 UTC, CubeDr commented on src/app/login/sign/page.js
> +    const validatePassword = (password) => {
함수 밖으로 빼주세요

2023-09-18 11:31 UTC, CubeDr commented on src/app/login/sign/page.js
> +    const passwordOnChange = (e) => {
여기도 이벤트를 처리랑 패스워드 변경 처리랑 로직 분리해보세요.

2023-09-18 11:31 UTC, CubeDr commented on src/app/login/sign/page.js
> +    const signUp = (e) => {
여기도 이벤트 처리 / 메인 로직 분리

2023-09-18 11:31 UTC, CubeDr commented on src/app/login/sign/page.js
> +        if ((password !== confirmPassword) || (passwordError !== "")) {
작은 따옴표

2023-09-18 11:31 UTC, CubeDr commented on src/app/login/sign/page.js
> +        if ((password !== confirmPassword) || (passwordError !== "")) {
그리고 소괄호 필요 없습니다

2023-09-18 11:31 UTC, CubeDr commented on src/app/login/sign/page.js
> +            alert("비밀번호를 다시 확인하세요");
작은 따옴표

2023-09-18 11:31 UTC, CubeDr commented on src/app/login/sign/page.js
> +            if (user) {
early-out

2023-09-18 11:31 UTC, CubeDr commented on src/app/mypage/page.js
> +export default function mypage() {
컴포넌트 이름은 대문자로

2023-09-18 11:31 UTC, CubeDr commented on src/app/mypage/page.js
> +            if (!user) {
early out

2023-09-18 11:31 UTC, CubeDr commented on src/app/mypage/page.js
> +                router.push("/login");
작은 따옴표

2023-09-18 11:31 UTC, CubeDr commented on src/app/mypage/page.js
> +}
빈 줄

2023-09-18 11:31 UTC, CubeDr commented on tailwind.config.js
> +    fontFamily: {
인덴트 맞춰주세요

2023-09-18 11:31 UTC, CubeDr commented on tailwind.config.js
> +        primary: {"50":"#eff6ff","100":"#dbeafe","200":"#bfdbfe","300":"#93c5fd","400":"#60a5fa","500":"#3b82f6","600":"#2563eb","700":"#1d4ed8","800":"#1e40af","900":"#1e3a8a","950":"#172554"}
작은 따옴표, 리포맷 해주세요

2023-09-18 17:30 UTC, judiking1 commented on src/app/globals.css
> +        @apply bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:plac
중간중간마다 엔터치면 되는 것 같긴한데.. 자동정렬하면 다시 한줄로 돌아오네

2023-09-18 22:21 UTC, CubeDr requested changes

2023-09-18 22:21 UTC, CubeDr commented on src/app/globals.css
> +        @apply bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:plac
@apply를 언제 사용하는지랑 사용하는 사례들 한 번 찾아보시는 게 좋을 것 같습니다.

2023-09-18 22:21 UTC, CubeDr commented on src/app/globals.css
> +}
빈 줄

2023-09-18 22:21 UTC, CubeDr commented on src/app/login/page.js
> +    const signInWithEmail = () => {
이름이 이거는 `signInWithEmail`인데 아래는 `snsSignin`입니다. 같은 규칙으로 통일해주세요.
`signInWithSns`로 바꾸시던 `emailSignin`으로 바꾸시던 해주세요

2023-09-18 22:21 UTC, CubeDr commented on src/app/login/sign/page.js
> +const validatePassword = (password) => {
함수 형식으로 정의해주세요

2023-09-18 22:21 UTC, CubeDr commented on src/app/login/sign/page.js
> +const validSingUp = () => {
함수 형식

2023-09-18 22:21 UTC, CubeDr commented on src/app/login/sign/page.js
> +        alert('비밀번호를 다시 확인하세요');
alert는 validate의 역할이 아닙니다. 이 함수에서는 비밀번호가 유효한지만 검사하고, 그에 따른 행동은 호출부에서 해주세요

2023-09-18 22:21 UTC, CubeDr commented on src/app/login/sign/page.js
> +        if (!validatePassword(password)) {
조건 반전시켜주세요

2023-09-18 22:21 UTC, CubeDr commented on src/app/login/sign/page.js
> +    const signUpWithEmail = () => {
이름 통일

2023-09-18 22:21 UTC, CubeDr commented on tailwind.config.js
> +                primary: { '50': '#eff6ff', '100': '#dbeafe', '200': '#bfdbfe', '300': '#93c5fd', '400': '#60a5fa', '500': '#3b82f6', '600': '#2563eb', '700': '#1d4ed8', '800': '#1e40af', '900': '#1e
마지막에 콤마 찍고 여러 줄로 분리해주세요

2023-09-18 22:21 UTC, CubeDr commented on tailwind.config.js
> +                'Noto Color Emoji'
콤마

2023-09-18 22:21 UTC, CubeDr commented on tailwind.config.js
> +                'Noto Color Emoji'
콤마

2023-09-19 05:25 UTC, judiking1 commented on src/app/globals.css
> +}
@apply는 같은 class들이 반복되는 요소들이 있을 때 재사용하기 위해서 쓰는듯.
단순히 html이 지저분해진다는 이유로 쓴다면 tailwind를 쓰는 목적과 맞지 않는 것 같음
여기선 login, sign 페이지에 중복되는 요소가 있어서 쓰긴 함

2023-09-19 09:35 UTC, CubeDr requested changes

2023-09-19 09:35 UTC, CubeDr commented on src/app/login/page.js
> +    const SignIn = (e) => {
sign in 전부 다 처리하는게 아니라 이메일 버튼을 눌렀을 때니까 sign in은 맞지 않습니다.
`onEmailSignInButtonClick` 정도로 바꿔주세요.

그리고 함수 이름은 camel case가 되어야 합니다.

2023-09-19 09:35 UTC, CubeDr commented on src/app/login/sign/page.js
> +    const signUp = (e) => {
여기도 이름 역할에 맞게 수정해주세요.

2023-09-19 09:35 UTC, CubeDr commented on src/app/login/sign/page.js
> +        return true;
`return password === confirmPassword && passwordError === '';`

2023-09-19 09:35 UTC, CubeDr commented on src/app/login/sign/page.js
> +    const passwordOnChange = (e) => {
`onPasswordChange`

2023-09-19 09:35 UTC, CubeDr commented on src/app/login/sign/page.js
> +        setPasswordError('A-Z, a-z, 0-9, 특수문자 포함, 8자 이상');
문자열 상수로 분리해주세요.

2023-09-19 09:35 UTC, CubeDr commented on src/app/globals.css
> +}
위에다 옮기겠습니다.

2023-09-19 09:35 UTC, CubeDr commented on src/app/globals.css
> +        @apply bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:plac
@judiking1 

> https://github.com/apply는 같은 class들이 반복되는 요소들이 있을 때 재사용하기 위해서 쓰는듯.
단순히 html이 지저분해진다는 이유로 쓴다면 tailwind를 쓰는 목적과 맞지 않는 것 같음
여기선 login, sign 페이지에 중복되는 요소가 있어서 쓰긴 함

그럼 이렇게 한 줄로 길게 늘어지는게 tailwind에서 의도한게 맞는건가요?

2023-09-19 10:04 UTC, judiking1 commented
기본적으로 tailwind은 class명으로 쓰는거라 한 줄로 길게 늘어질 수밖에 없는 구조인듯.
대신에 그게 보기 힘들면 저렇게 @apply를 써서 html상에선 보기좋게 할 수도 있는 거고.
애초에 tailwind의 장점은 사용이 편리한거고 단점은 저렇게 길게 늘여져서 보기 안좋은것이라 하네

2023-09-19 11:22 UTC, CubeDr approved these changes

2023-09-19 11:22 UTC, CubeDr commented
알겠습니다. 굉장히 별로군요.
진행중인 대화에 대한 답변은 해당 대화에 달아주세요.

2023-09-19 11:23 UTC, CubeDr requested changes

2023-09-19 11:23 UTC, CubeDr commented on src/app/login/sign/page.js
> +const pwErr = 'A-Z, a-z, 0-9, 특수문자 포함, 8자 이상';
`reg`랑 `validatePassword`가 한 묶음이니 `pwErr`는 분리해서 써주세요.

2023-09-19 11:24 UTC, CubeDr requested changes

2023-09-19 11:24 UTC, CubeDr commented on src/app/login/sign/page.js
> +const pwErr = 'A-Z, a-z, 0-9, 특수문자 포함, 8자 이상';
상수들은 다 대문자로 써주세요.
https://google.github.io/styleguide/jsguide.html#naming-constant-names

2023-09-19 11:50 UTC, CubeDr requested changes

2023-09-19 11:50 UTC, CubeDr commented on src/app/login/sign/page.js
> +const PWERR = 'A-Z, a-z, 0-9, 특수문자 포함, 8자 이상';
위에 한 줄 추가해주시죠

2023-09-19 14:09 UTC, CubeDr approved these changes

2023-09-19 14:31 UTC, merged